### ISSUE TITLE
Automatically set path of asan on windows

### ISSUE THREAD

**Issue by cor3ntin** [mod-cpp/pacman#21]
Put the path of the lib in the path

**Comment by patricia-gallardo** [comment]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\Hostx86\x86;

**Comment by patricia-gallardo** [comment]
---------------------------
pacman_tests.exe - System Error
---------------------------
The code execution cannot proceed because clang_rt.asan_dbg_dynamic-i386.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------

**Comment by olafurw** [comment]
Fixed by b55e654cceba1f0023543ea075df382c3ac25134
